### PR TITLE
Update Sbmanager code with code that has fixes for many depreciations in library's used.

### PR DESCRIPTION
**Pull request by gitsop01**
Still a work in progress due to the changes in Fedora, Gnome 3, Gtk3 and Clutter libraries
Although a lot of debugging code and comments are included in the pull request it updates the sbmanager code to remove many library function depreciations and is therefore more up to date.

### CODE REVIEW

**Review by glensc — CHANGES_REQUESTED** [review]
first of all: when making Pull-Request, you should never use `master` to do so, because you can't use your `master` branch for your own purposes anymore.

secondly, your commits are really "dirty" here, they should be cleaned up, merge commits removed (squashed) some useless changes also removed.

also should remove generated files and add their pattern to `.gitignore`. these include compiled po and intltool-merge-cache

there's also some debug committed in: `printf("in main1")`

i understand your code is not ready, but you should keep your development branch (`master`) and code you wish to submit upstream (this PR) on separate branches.

this is not official comment from maintainers, i'm just throwing out some common reasons why PR's don't get merged. but here i guess just there is no maintainer :D. but then again, if your PR is really nice (cleaned up, etc) someone from @libimobiledevice group could just merge it.

**Comment by gitsop01** [comment]
Thanks for the info about pull request,  All comments noted,

**Comment by nikias** [comment]
This can't be merged as is, as @glensc already stated. We can't accept commits with a commit message "Signed-off-by:" or "Merge branch ***".
Every commit needs to make clear what the commit is for.
Also commented-out code isn't really what you want in git and you don't actually need that in a version control system anyway.

**Comment by gitsop01** [comment]
As @glensc stated the pull should be from  a branch and not off the
master. I have noted the comments about
the commit messages and the commented out code and will update in a
branch. 
Would you please close this pull request .

**Comment by glensc** [comment]
@gitsop01 you as author of the PR can close PR yourself.

**Comment by gitsop01** [comment]
Pull request closed as code requires clean-up and pulling from a branch.

**Pull request closed without merging**
